### ISSUE TITLE
这语法看不懂啦

### ISSUE THREAD

**Issue by luqin** [react-china/discourse-reader#1]
这语法看不懂啦 :smile:

**Comment by tiye** [comment]
楼上要先能写 Clojure, 能配 Leiningen 环境, 能写 ClojureScript.
然后我的代码是通过 `lein cirru-sepal` 命令自动生成大量括号的.

**Comment by luqin** [comment]
太复杂了，哈哈

**Comment by tiye** [comment]
Clojure 的话需要自己学了
reagent 的话文档在这里, 我计划翻译一遍 http://reagent-project.github.io/

**Comment by luqin** [comment]
成本倒是略高啊

**Comment by tiye** [comment]
@luqin 所以我自己一个人维护也就好了... 底层运行的是还是 React 和 JavaScript 还有不可变数据, 这方面还是可以一起商量下
